# Generated by Django 3.1.7 on 2021-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdata',
            name='belong_flag',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='归属标识'),
        ),
        migrations.AddField(
            model_name='serverdata',
            name='cloud',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='云平台'),
        ),
        migrations.AddField(
            model_name='serverdata',
            name='zone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='cpu',
            field=models.IntegerField(verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='create_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='expired_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='ipv4',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ipv4地址'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='memory',
            field=models.IntegerField(verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='os',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='状态'),
        ),
    ]
