# Generated by Django 3.1.5 on 2021-12-27 10:31

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=64, verbose_name='申请应用名称')),
                ('apply_member', models.CharField(max_length=64, verbose_name='申请人')),
                ('responsible_member', models.CharField(max_length=64, verbose_name='责任人')),
                ('app', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6, verbose_name='申请应用')),
                ('app_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='应用名称')),
                ('cache', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6, verbose_name='缓存')),
                ('msg_middleware', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6, verbose_name='消息中间件')),
                ('db', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6, verbose_name='数据库')),
                ('zone', models.CharField(blank=True, max_length=64, null=True, verbose_name='云环境')),
                ('env', models.CharField(max_length=64, verbose_name='环境')),
                ('resources', models.JSONField(blank=True, max_length=255, null=True, verbose_name='资源')),
                ('domain', models.JSONField(blank=True, max_length=255, null=True, verbose_name='域名')),
                ('approve_check', models.BooleanField(default=False, verbose_name='审批确认完成')),
            ],
        ),
        migrations.CreateModel(
            name='CheckApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.BooleanField(default=False, verbose_name='第一步')),
                ('second', models.BooleanField(default=False, verbose_name='第二步')),
                ('third', models.BooleanField(default=False, verbose_name='第三步')),
                ('end', models.BooleanField(default=False, verbose_name='结束')),
                ('approve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approve.approve')),
            ],
        ),
    ]
